### ISSUE TITLE
[JobController] Runs are duplicated in the database

### ISSUE THREAD

**Issue by keiranjprice101** [interactivereduction/jobcontroller#144]
### Description of the issue

Runs are duplicated in the database. This seems to happen as, when a sum run happens, a new run is created in the run table, even if it previously exists from the non sum version.

This could probably be fixed by creating a `get_or_create` functionality.

As part of this being resolved we should run a one time SQL script to remove the duplicate entries and fix the junction table

**Comment by Pasarus** [comment]
Fixed as part of the Jobcreator and jobwatcher work.
